[build]
  base = "alumni-frontend"
  command = "npm ci && npx ng build --configuration production"
  publish = "dist/alumni-frontend"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
